### PR TITLE
fix: ignore reviewpad check runs by default

### LINKED ISSUE #655: $haveAllChecksRunCompleted built-in does not ignore reviewpad check
**Describe the bug**
Currently, the built-in `haveAllChecksRunCompleted` does not ignore the reviewpad check. This causes the built-in to always return `false` since the Reviewpad check is always running when the built-in is triggered.
 
**To Reproduce**
1. Define a Reviewpad configuration that uses the built-in `haveAllChecksRunCompleted`
2. Open a pull request to trigger Reviewpad
3. You will see that the workflow using the built-in `haveAllChecksRunCompleted` will never be triggered regardless of the check run status.

**Expected behavior**
The built-in `haveAllChecksRunCompleted` should ignore the Reviewpad check in order to work properly.

### PR DESCRIPTION
**Pull request by ferreiratiago**
## Description

This pull request introduces the fix to the built-in `haveAllChecksRunCompleted` by ignoring the Reviewpad check by default.

## Related issue

Closes #655

## Type of change

Bug fix (non-breaking change which fixes an issue)

## How was this tested?

Manuel tests

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 

- [x] Ask: this pull request requires a code review before merge

### CODE REVIEW

**Review by zolamk — APPROVED** [review]

File: plugins/aladino/functions/haveAllChecksRunCompleted_test.go [hunk 1]
```diff
@@ -389,6 +389,49 @@ func TestHaveAllChecksRunCompleted(t *testing.T) {
 			},
 			wantResult: aladino.BuildBoolValue(true),
 		},
+		"when reviewpad is one of the checks": {
```
Comment (shay2025) [inline plugins/aladino/functions/haveAllChecksRunCompleted_test.go:392]: Shouldn't we have two test cases where reviewpad is one of the checks and:
- the check runs have all been completed;
- not all check runs have been completed.

**Review by shay2025 — APPROVED** [review]
Just a thought

File: plugins/aladino/functions/haveAllChecksRunCompleted_test.go (hunk 1 above)
Comment (ferreiratiago) [reply plugins/aladino/functions/haveAllChecksRunCompleted_test.go:392]: I see. There's no need for that. The important thing here is for the Reviewpad check to be ignored regardless of the other checks' status.
