### PR TITLE
fix: don't re-request review unless a new commit has been pushed

### LINKED ISSUE #415: Re-requesting a review from a user with a updated review
**Describe the bug**
For some reason, reviewpad re-requests a review from a user with an updated review. By updated it means that the user did a review and no changes were added since.

**To Reproduce**
- Open a pr
- Reviewpad requests a review from user X
- User X makes a `request changes` review
- Reviewpad runs and re-requests a review

**Expected behavior**
- Reviewpad shouldn't re-request a review when the user has an updated review (regardless of review type - i.e. approved, requested changes, commented).

**Screenshots**
The problem can be seen in the following pr https://github.com/reviewpad/reviewpad/pull/412

Screen Shot 2022-10-24 at 8 49 03 PM

### PR DESCRIPTION
**Pull request by zolamk**
## Description
This PR updates the `$assignReviewer` built-in action so that it checks the last pushed date before re-requesting a review

## Related issue

Closes #415 

## Type of change

Improvements (non-breaking change without functionality)

## How was this tested?
Unit tests and manual tests

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before merge

### CODE REVIEW

File: plugins/aladino/actions/assignReviewer.go [hunk 1]
```diff
@@ -71,12 +76,17 @@ func assignReviewerCode(e aladino.Env, args []aladino.Value) error {
 		return err
 	}
 
+	lastPushDate, err := e.GetGithubClient().GetPullRequestLastPushDate(ctx, owner, repo, prNum)
+	if err != nil {
+		return err
+	}
```
Comment (ferreiratiago) [inline plugins/aladino/actions/assignReviewer.go:82]: This is not the right way to do it. We should do this on `target` which already has the client in it.

Please have a look at `codehost/github/target/pull_request_target.go`.

**Review by ferreiratiago — APPROVED** [review]
