### PR TITLE
fix: close built-in failing

### LINKED ISSUE #602: `$close` built-in is failing
**Describe the bug**
The `$close` built-in seems to be failing in the GitHub App but not in the GitHub Action with the following error:
`422 Validation Failed [{Resource:PullRequest Field:maintainer_can_modify Code:invalid Message:Only the pull request author may change the maintainer_can_modify value}]`.

**To Reproduce**
1. Add, to the `reviewpad.yml` file, a workflow with the `$close` action and a rule that will be activated.
2. Open a pull request.

**Expected behavior**
The built-in should not fail.

### PR DESCRIPTION
**Pull request by shay2025**
## Description

This pull request introduces the fixes for the failure of the `$close` built-in by replacing the REST API requests with GraphQL requests.

## Related issue

Closes #602 

## Type of change

Bug fix (non-breaking change which fixes an issue)

## How was this tested?

Manual tests and ran `task check` cmd.

## Checklist

- [x] I have performed a self-review of my code
- [x] I have added tests that prove my fix is effective or that my feature works 
- [x] I have run `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 
 
- [x] Ask: this pull request requires a code review before the merge

### CODE REVIEW

File: plugins/aladino/actions/close_test.go [hunk 1]
```diff
@@ -20,56 +21,289 @@ import (
...
+		t.Run(name, func(t *testing.T) {
+			args := []aladino.Value{aladino.BuildStringValue(""), aladino.BuildStringValue(test.inputStateReason)}
+			gotErr := close(test.mockedEnv, args)
+
+			assert.EqualError(t, gotErr, test.wantErr)
+		})
+	}
+}
+
+func TestClose_WhenCommenteRequestFails(t *testing.T) {
```
Comment (ferreiratiago) [inline plugins/aladino/actions/close_test.go:122]:
```suggestion
func TestClose_WhenCommentRequestFails(t *testing.T) {
```

File: plugins/aladino/functions/context_test.go [hunk 2]
```diff
@@ -29,12 +29,12 @@ func TestContext(t *testing.T) {
...
-				"id": 2,
+                "id": 2,
 				"name": "large"
 			}
-        ],
-        "user": {
-            "login": "john"
+            ],
+            "user": {
+                "login": "john"
```
Comment (ferreiratiago) [inline plugins/aladino/functions/context_test.go:37]: Please fix this indentation.

**Review by ferreiratiago — CHANGES_REQUESTED** [review]

File: plugins/aladino/functions/context_test.go [hunk 3]
```diff
@@ -29,7 +29,7 @@ func TestContext(t *testing.T) {
                 "name": "enhancement"
             },
 			{
-				"id": 2,
+                "id": 2,
 				"name": "large"
 			}
```
Comment (shay2025) [inline plugins/aladino/functions/context_test.go:34]: @ferreiratiago  It's very strange that it appears like this even with `task format`, on my IDE it looks just fine
image

**Review by ferreiratiago — APPROVED** [review]
